---
- hosts: all
  become: true
  tasks:

  - name: install apache2 packages
    ansible.builtin.apt:
      update_cache: yes
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_facts['os_family'] == "Debian"

  - name: install httpd packages
    ansible.builtin.dnf:
      update_cache: yes
      name:
        - httpd
        - php
      state: latest
    when: ansible_facts['os_family'] == "RedHat"
