---
- hosts: all
  become: true
  pre_tasks:

  - name: Install updates for Fedora
    tags: always
    ansible.builtin.dnf:
      update_cache: yes
      update_only: yes
    when: ansible_facts['os_family'] == "RedHat"

  - name: Install updates for Debian
    tags: always
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist
    when: ansible_facts['os_family'] == "Debian"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb on db servers
    tags: db,fedora
    ansible.builtin.dnf:
      name: mariadb
      state: absent
    when: ansible_facts['os_family'] == "RedHat"

- hosts: web_servers
  become: true
  tasks:

  - name: Install apache on debian web servers
    tags: apache
    ansible.builtin.apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_facts['os_family'] == "Debian"

  - name: Install apache on fedora web servers
    tags: apache
    ansible.builtin.dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_facts['os_family'] == "RedHat"

  - name: copy default html file for web site
    tags: apache
    ansible.builtin.copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
