- name: Install packages for Fedora
  tags: always
  ansible.builtin.dnf:
    name:
      - dnf-utils
      - fastfetch
      - nano
    state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: Install packages for Debian
  tags: always
  ansible.builtin.apt:
    name:
      - fastfetch
      - vim
    state: latest
  when: ansible_facts['os_family'] == "Debian"

-  name: Create user ansible
   tags: always
   ansible.builtin.user:
     name: ansible
     shell: /bin/bash
     groups: root

- name: Add sudoers file for ansible
  tags: always
  ansible.builtin.copy:
    src: sudoer_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: Add authorized key for ansible
  tags: always
  ansible.builtin.authorized_key:
    user: ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKFM7jdkwWE920yK2+lGHfQnYisSxKfSkSxpLKpPM7mb bjh-ansible"

